export const animals = [
  { name: "shoes" },
  { name: "tshirt" },
  { name: "pants" },
  { name: "bags" },
  { name: "sneaker" },
  { name: "hat" },
  { name: "footwear" },
  { name: "gown" },
  { name: "shirt" },
  { name: "swimwear" },
  { name: "scarf" },
  { name: "spider" },
  { name: "squirrel" },
  { name: "tapir" },
  { name: "tarsier" },
  { name: "tiger" },
  { name: "wallaby" },
  { name: "walrus" },
  { name: "water-buffalo" },
  { name: "weasel" },
  { name: "wolf" },
  { name: "wombat" },
  { name: "yak" },
  { name: "zebra" },
];
